# name: Deployment pipeline

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches: [main]
#     types: [opened, synchronize]

# jobs:
#   simple_deployment_pipeline:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: "20"
#       - name: Install dependencies
#         run: npm install
#       - name: Check style
#         run: npm run eslint
#       - name: Build for production
#         run: npm run build
#       - name: Test - Jest
#         run: npm run test
#       - name: E2E-test - 1.Install Playwright Browsers
#         run: npx playwright install --with-deps
#       - name: E2E-test - 2.Run Playwright tests
#         run: npm run test:e2e
#       - uses: actions/upload-artifact@v4
#         if: ${{ !cancelled() }}
#         with:
#           name: playwright-report
#           path: playwright-report/
#           retention-days: 30
#       - name: Trigger deployment
#         run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
#         if: ${{ github.event_name == 'push' }}   

#   tag_release:
#     needs: [simple_deployment_pipeline]
#     runs-on: ubuntu-latest
#     if: ${{ github.event_name == 'push' }}
#     steps:
#       - uses: actions/checkout@v4
#       - name: Bump version and push tag
#         uses: anothrNick/github-tag-action@1.73.0
#         env:
#           GITHUB_TOKEN: ${{ github.token }}
#           DEFAULT_BUMP: patch

name: Testing stuff

env: 
  CONDITION: ${{ contains(join(github.event.commits.*.message, ', '), '#skip') }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: github context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"
      # - name: commits
      #   env:
      #     COMMITS: ${{ toJson(github.event.commits) }}
      #   run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: join all commit messages
        run: echo "$COMMIT_MESSAGES"
      - name: if commit messages included special piece in push action
        if: ${{ github.event_name == 'push' && env.CONDITION == 'true' }}
        run: echo "skip deploy and tag, due to push action commit message"
      - name: if commit messages included special piece in pull request action
        if: ${{ github.event_name == 'pull_request' && env.CONDITION == 'true' }}
        run: echo "skip deploy and tag, due to pull-request action commit message"